services:
  place:
    image: place
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: ["--width", "2560", "--height", "1440", "--save-location", "/place/place.png", "--save_all_images","true"]
    volumes:
      - ./data:/place
    restart: unless-stopped

  nginx:
    image: place-nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    restart: unless-stopped
