services:
  place:
    image: place
    build:
      context: ./server
    volumes:
      - ./data:/place
    networks:
      - ip6net
    restart: unless-stopped

  nginx:
    image: place-nginx
    build:
      context: ./nginx
    ports:
      - "${PORT}:80"
    restart: unless-stopped
    depends_on:
      - place

networks:
   ip6net:
     enable_ipv6: true