services:
  place:
    image: place
    build:
      context: ./server
    volumes:
      - ./data:/place
    restart: unless-stopped

  nginx:
    image: place-nginx
    build:
      context: ./nginx
    ports:
      - "${PORT}:8001"
    restart: unless-stopped
    depends_on:
      - place
