version: "3"
services:
  nginx:
    image: place-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - place

  place:
    image: place
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - WIDTH=${WIDTH}
      - HEIGHT=${HEIGHT}
      - SAVE_INTERVAL=${SAVE_INTERVAL}
      - PLACE_FILE=${PLACE_FILE}
    volumes:
      - ./data:/place
