services:
  place:
    image: place
    build:
      context: ./server/
    volumes:
      - ./data:/place
    restart: unless-stopped

  nginx:
    image: place-nginx
    build:
      context: ./nginx/
    ports:
      - "${PORT}:80"
    restart: unless-stopped
