version: "3"
services:
  place:
    image: place
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./data:/place
    restart: always

  nginx:
    image: place-nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    restart: always
