services:
  place:
    image: place
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./data:/place
    restart: unless-stopped

  nginx:
    image: place-nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
